config-version: '1.0'
# Do not change this unless you really know what you're doing!

override-enchanting-table: true
# Replace the vanilla enchanting table with the custom enchanting gui.

play-sound-on-enchant: true
# Whether or not to play a sound effect when the player enchants an item

gui-info:
  fill-inventory: true
  # Whether or not to fill the enchanting gui with glass panes
  inventory-name: 'Enchanting Table'
  # Can use FontImages for custom GUI
  tool-slot: 10
  # Inventory slot for the tool being enchanted
  material-slot: 12
  # Inventory slot for the material you're enchanting with
  cost-preview-slot: 14
  # Inventory slot for the arrow icon that shows the cost
  result-slot: 16
  # Inventory slot that the resulting enchanted item shows up on
  cost-preview-item:
    material: ENCHANTED_BOOK
#    material: icon_right_blue
#    custom-material:
#      source: "itemsadder"
#      namespace: "_iainternal"





