name: NouveauEnchanting
version: '${version}'
main: us.to.midensthings.nouveauEnchanting.NouveauEnchanting
api-version: '26.1.2'
bootstrapper: us.to.midensthings.nouveauEnchanting.NouveauEnchantingBootstrapper

dependencies:
  server:
    ItemsAdder:
      load: BEFORE
      required: false
      join-classpath: true

commands:
  nedebug:
    description: "Debug command for Nouveau Enchanting"
    usage: "/nedebug"
    permission: nouveauenchanting.commands.debug
  ne:
    description: "Core for Nouveau Enchanting"
    usage: "/ne"
    permission: nouveauenchanting.commands.core

permissions:
  nouveauenchanting.commands.debug:
    default: op
    description: "Allows use of debug commands."
  nouveauenchanting.commands.reload:
    default: op
    description: "Allows use of /ne reload"
  nouveauenchanting.commands.gui:
    default: op
    description: "Allows use of /ne opengui"
  nouveauenchanting.commands.gui.other:
    default: op
    description: "Allows use of /ne opengui [player]"
  nouveauenchanting.commands.core:
    default: op
    description: "Allows use of /ne"